name: shule_point_app
description: Mobile client for parents & students to see their school & class information on the ShulePoint students management system.

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.5
    intl: ^0.19.0
    http: ^1.2.1
    dio: ^5.1.1
    lottie: ^3.1.0
    flutter_easyloading: ^3.0.5
    modals: ^1.0.0
    rounded_loading_button_plus: ^3.0.1
    flutter_spinkit: ^5.1.0
    awesome_dialog: ^3.0.2
    flutter_secure_storage: ^9.0.0
    flutter_dotenv: ^5.0.2
    font_awesome_flutter: ^10.4.0
    page_transition: '^2.0.2'
    image_picker: ^1.1.0
    image_cropper: ^5.0.1
    flutter_svg: ^2.0.5

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^3.0.2
    flutter_launcher_icons: ^0.13.0
    flutter_native_splash: ^2.2.16
    # flutter_app_name: ^0.1.0

flutter_app_name:
    name: 'shulePoint'

flutter_icons:
    android: 'launcher_icon'
    ios: true
    image_path: 'assets/icon/AppIcon.png'

flutter:
    uses-material-design: true

    assets:
        - .env
        - .env.dev
        - assets/images/
        - assets/images/characters/
        - assets/images/pageBanners/
        - assets/lottieAnimations/

    fonts:
        - family: Rajdhani
          fonts:
              - asset: assets/fonts/Rajdhani/Rajdhani-Light.ttf
                weight: 300
              - asset: assets/fonts/Rajdhani/Rajdhani-Regular.ttf
                weight: 400
              - asset: assets/fonts/Rajdhani/Rajdhani-Medium.ttf
                weight: 500
              - asset: assets/fonts/Rajdhani/Rajdhani-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/Rajdhani/Rajdhani-Bold.ttf
                weight: 700
